# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateField(verbose_name='checkout date')),
                ('checkin_date', models.DateField(verbose_name='checkin date')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=20)),
                ('model_number', models.CharField(max_length=50)),
                ('purchase_date', models.DateField(verbose_name='date purchased')),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='authorizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorizer', to='checkout.User'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrower', to='checkout.User'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Item'),
        ),
    ]
