# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_item_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='item',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
