# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20160323_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkin_date',
            field=models.DateField(null=True, verbose_name='checkin date'),
        ),
    ]
