# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='kit_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='model_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
