# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20160420_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
