# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 23:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_auto_20160425_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='authorizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorizer', to=settings.AUTH_USER_MODEL),
        ),
    ]
